version: '3.8'

services:
  backend:
    build:
      context: ./backendAipos7/docker
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/aipos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  frontend:
    build:
      context: ./frontendAipos7/docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BACKEND_URL: http://backend:8081
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aipos
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge